@HostAddress = https://localhost:7522/api/v1
@JwtToken = YOUR_GENERATED_JWT_TOKEN

### 
GET {{HostAddress}}/forex/eur
Accept: application/json
Authorization: Bearer {{JwtToken}}

###
GET {{HostAddress}}/forex/usd/exchange/aud
Accept: application/json
Authorization: Bearer {{JwtToken}}

###
GET {{HostAddress}}/forex/eur/exchange/aud?amount=1000
Accept: application/json
Authorization: Bearer {{JwtToken}}

###
GET {{HostAddress}}/forex/eur/exchange/try
Accept: application/json
Authorization: Bearer {{JwtToken}}

###
GET {{HostAddress}}/forex/eur/history?startDate=2025-02-08
Accept: application/json
Authorization: Bearer {{JwtToken}}

###
GET {{HostAddress}}/forex/eur/history?startDate=2025-02-07&endDate=2025-02-10
Accept: application/json
Authorization: Bearer {{JwtToken}}

###
GET {{HostAddress}}/forex/eur/history?startDate=2025-02-07&endDate=2025-02-01
Accept: application/json
Authorization: Bearer {{JwtToken}}

###
